### ISSUE TITLE
Issue setting up the project

### ISSUE THREAD

**Issue by ezratechdev** [Andrea055/nodeMyAdmin#1]
Hello i would love to contribute to the project , i am quite new to svelte but i am going throught it's docs and trying to catch up
Despite this i am facing some issues while trying to setup the project ie : failed to load module for ssr: /src/lib/crypto/aes
Would it be possible to setup a readMe that details how to setup the project ?

**Comment by andreock** [comment]
I will create a section with this information. Anyway, probably you need to create a .env with key and iv. Explained here: https://andrea055.github.io/nodeMyAdmin.github.io/download/
