### ISSUE TITLE
Error: Invalid passphrase

### ISSUE THREAD

**Issue by adamrpostjr** [Andrea055/nodeMyAdmin#6]
To reproduce:
Clone repo and run `yarn start`
Download Release unzip and run `node ./server.js`

OS: Windows 11 Pro x86_64
Host: ASUS
Kernel: 10.0.22000
Uptime: 5 hours, 16 mins
Packages: 2 (scoop)
Shell: bash 5.1.16
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Custom
Terminal: Windows Terminal
CPU: Intel i3-10100 (8) @ 3.600GHz
GPU: Caption
GPU: NVIDIA GeForce GTX 750 Ti
GPU
Memory: 16440MiB / 32621MiB

**Comment by andreock** [comment]
You need to set password in config.json, here more details: https://andrea055.github.io/nodeMyAdmin.github.io/download/
I will add this to readme, thanks for feedback!
